### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by agarzon48** [AlvaroMartinFernandez/Instagram-Feed#1]
- Las imágenes deberían ir en su propia carpeta (img, assets o similar)
- Las imágenes del grid deben visualizarse con el mismo tamaño aunque tengan aspects-ratio diferentes
- Los textos de las cards (vista lista) deberían tener un padding

- Muy bien gestionado el grid en responsive

**Comment by AlvaroMartinFernandez** [comment]
Buenas,

- Imagenes en su propia carpeta en assets/img.
- clase ratio de bootstrap usada para dar el mismo tamaño a todas las imagenes.
- padding en los textos de las cards.

**Comment by agarzon48** [comment]
Perfecto!
